import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { parse as parseYaml, stringify as stringifyYaml } from 'yaml'

export const LOCKFILE_VERSION = 1
export const LOCKFILE_NAME = 'speq.lock'

export interface LockedPackage {
  resolved: string
  integrity: string
  /** Exact versions, so the graph replays without touching the registry. */
  dependencies?: Record<string, string>
}

export interface LockedRoot {
  /** What speq.yaml asked for, verbatim. */
  spec: string
  name: string
  version: string
}

export interface LockFile {
  lockfileVersion: number
  /** Packages named by `extends`. Locked separately: they decide the rest. */
  presets: LockedRoot[]
  plugins: LockedRoot[]
  packages: Record<string, LockedPackage>
}

/**
 * The lock is the only thing about the plugin set that a service repository
 * commits. It exists so that `--frozen` in CI installs bit-for-bit what a
 * developer installed, which is the guarantee `brew install speq` cannot make
 * and the reason plugin sets drift across thirty repositories.
 */
export function readLock(root: string): LockFile | undefined {
  const file = join(root, LOCKFILE_NAME)
  if (!existsSync(file)) return undefined

  const parsed = parseYaml(readFileSync(file, 'utf8')) as LockFile | null
  if (!parsed) return undefined
  if (parsed.lockfileVersion !== LOCKFILE_VERSION) {
    throw new Error(
      `${file} is lockfile version ${parsed.lockfileVersion}; this build writes version ${LOCKFILE_VERSION}. ` +
        `Delete it and run 'speq install'.`
    )
  }
  return {
    lockfileVersion: parsed.lockfileVersion,
    presets: parsed.presets ?? [],
    plugins: parsed.plugins ?? [],
    packages: parsed.packages ?? {}
  }
}

export function writeLock(root: string, lock: LockFile): string {
  const file = join(root, LOCKFILE_NAME)
  const ordered: LockFile = {
    lockfileVersion: LOCKFILE_VERSION,
    presets: lock.presets,
    plugins: lock.plugins,
    // Sorted, so two developers installing the same set produce the same
    // file and the diff is about the change, not about map ordering.
    packages: Object.fromEntries(Object.entries(lock.packages).sort(([a], [b]) => a.localeCompare(b)))
  }
  writeFileSync(
    file,
    `# Generated by speq. Commit this file.\n` +
      `# Exact versions and hashes of every plugin and its dependencies.\n\n` +
      stringifyYaml(ordered, { lineWidth: 0 })
  )
  return file
}

export function keyOf(name: string, version: string): string {
  return `${name}@${version}`
}

export function parseKey(key: string): { name: string; version: string } {
  const at = key.lastIndexOf('@')
  if (at <= 0) throw new Error(`malformed lock entry '${key}'`)
  return { name: key.slice(0, at), version: key.slice(at + 1) }
}
