export { discoverRoot, type SpeqRoot, type LayoutMode } from './discovery.js'
export { loadConfig, type SpeqConfig } from './config.js'
export { loadPlugins } from './plugins.js'
export { discoverTests, type DiscoverOptions } from './tests.js'
export { validateTests, type Diagnostic } from './validate.js'
export { runTests, type RunOutcome, type TestOutcome } from './runner.js'
export { Registry, shortName } from './registry.js'
export { Executor } from './executor.js'
export { EventBus } from './events.js'
export { resolveDeep, resolveString, UnresolvedError } from './interpolate.js'
export { bootstrap, type Session } from './bootstrap.js'
