export { discoverRoot, type SpeqRoot, type LayoutMode } from './discovery.js'
export { loadConfig, readRawConfig, type SpeqConfig } from './config.js'
export { addPluginToConfig, removePluginFromConfig } from './edit-config.js'
export { loadPlugins, resolvePlugin, type PluginSource, type PluginOrigin } from './plugins.js'
export { discoverTests, type DiscoverOptions } from './tests.js'
export { validateTests, type Diagnostic } from './validate.js'
export { runTests, type RunOutcome, type TestOutcome, type RunOptions } from './runner.js'
export { ArtifactStore, type ArtifactRecord } from './artifacts.js'
export { Registry, shortName } from './registry.js'
export { Executor } from './executor.js'
export { EventBus } from './events.js'
export { resolveDeep, resolveString, UnresolvedError } from './interpolate.js'
export { bootstrap, type Session } from './bootstrap.js'
