import type { Capabilities, Capability, InputSchema } from '@speqkit/plugin-api'

/**
 * The grammar of this project, as a JSON Schema an editor can read.
 *
 * `speq validate` has known the whole vocabulary since the first release and
 * an editor has known none of it: a step type is a word a plugin registered at
 * load time, so no schema shipped in a package could ever list the ones this
 * project has. The site has promised for two releases that "plugin schemas are
 * handed to yaml-language-server", and nothing in the code did it.
 *
 * Generated from `host.capabilities()` — the running session, with exactly the
 * plugins this project loads — which is also the honest limit of it: the file
 * is a snapshot and goes stale when the plugins change. That is why it is a
 * command somebody runs rather than something written once by `speq init` and
 * quietly wrong six weeks later.
 *
 * What it cannot be is the check. `validate` reads references, forward
 * declarations, duplicate ids and whatever each plugin's own `validate` knows,
 * none of which is expressible here. This is completion and a red squiggle on
 * a misspelled key; the answer still comes from `speq validate`.
 */
export function editorSchema(capabilities: Capabilities): Record<string, unknown> {
  const plugins = capabilities.plugins.map((p) => (p.version ? `${p.name} ${p.version}` : p.name))

  return {
    $schema: 'http://json-schema.org/draft-07/schema#',
    title: 'speq test',
    description:
      `Generated by 'speq schema' from the plugins this project loads: ${plugins.join(', ')}. ` +
      'Re-run it after adding or removing one. Completion and shapes only — ' +
      "references, forward declarations and each plugin's own checks are 'speq validate'.",
    definitions: {
      steps: {
        type: 'array',
        description: 'steps, run in order; the first one that fails stops the block',
        items: { $ref: '#/definitions/step' }
      },
      step: step(capabilities.stepTypes),
      assertions: {
        type: 'array',
        description: 'checks over what the steps produced',
        items: { $ref: '#/definitions/assertion' }
      },
      assertion: assertion(capabilities.assertions),
      test: test(),
      suite: suite()
    },
    // Either kind of file, because one schema line in an editor's settings
    // covers a directory and a suite manifest lives in the same directory as
    // the tests. A test file and a manifest are told apart by what they carry.
    anyOf: [{ $ref: '#/definitions/test' }, { $ref: '#/definitions/suite' }]
  }
}

/** Everything the kernel owns on a step, whatever its type. */
const STEP_SPINE: Record<string, unknown> = {
  id: { type: 'string', description: 'binds this step\'s result, addressable below as ${id.field}' },
  type: { type: 'string' },
  when: {
    type: ['string', 'boolean'],
    description: 'run this step only if the value is true; otherwise it is skipped'
  },
  timeout: {
    type: ['integer', 'string'],
    description: "the longest this step may take — 5000, or '30s'"
  },
  assert: { $ref: '#/definitions/assertions' },
  meta: { type: 'object', description: 'annotations, carried and never read' }
}

function step(types: Capability[]): Record<string, unknown> {
  return {
    type: 'object',
    required: ['type'],
    properties: {
      ...STEP_SPINE,
      type: {
        type: 'string',
        description: 'what this step does; every one of these was contributed by a loaded plugin',
        // Not `enum`: an unknown type has to be a squiggle rather than a
        // refusal to say anything about the rest of the file, and the list is
        // still what completion offers.
        examples: types.map((t) => t.name)
      }
    },
    allOf: types.map((entry) => ({
      if: { properties: { type: { const: entry.name } }, required: ['type'] },
      then: shapeOf(entry)
    }))
  }
}

function assertion(types: Capability[]): Record<string, unknown> {
  return {
    type: 'object',
    required: ['type'],
    properties: {
      type: {
        type: 'string',
        description: 'the check to make',
        examples: types.map((t) => t.name)
      },
      meta: { type: 'object', description: 'annotations, carried and never read' }
    },
    allOf: types.map((entry) => ({
      if: { properties: { type: { const: entry.name } }, required: ['type'] },
      then: shapeOf(entry, { type: { type: 'string' }, meta: { type: 'object' } })
    }))
  }
}

/**
 * One capability's own schema, with the kernel's fields added back.
 *
 * `additionalProperties: false` is what makes a misspelled key visible, and it
 * only sees the properties declared beside it — so the spine has to be written
 * into every branch or `id:` would be the mistake instead.
 */
function shapeOf(entry: Capability, spine: Record<string, unknown> = STEP_SPINE): Record<string, unknown> {
  const schema = entry.schema
  if (!schema) return { description: entry.summary ?? '' }

  const properties: Record<string, unknown> = { ...spine }
  for (const [name, value] of Object.entries(schema.properties ?? {})) {
    properties[name] = templatable(value)
  }

  return {
    ...(entry.summary ? { description: entry.summary } : {}),
    type: 'object',
    properties,
    ...(schema.required?.length ? { required: schema.required } : {}),
    ...(schema.additionalProperties === false ? { additionalProperties: false } : {})
  }
}

/**
 * A field of any type may be written as a whole `${…}`.
 *
 * `status: "${expected}"` is a string in the file and a number by the time the
 * step sees it, and the kernel's own checker has always allowed that. An
 * editor that did not would put a red line under the correct way to write it,
 * which is worse than saying nothing.
 */
function templatable(schema: unknown): unknown {
  if (!schema || typeof schema !== 'object' || Array.isArray(schema)) return schema
  const node = schema as InputSchema
  const type = node.type

  const inner: Record<string, unknown> = { ...node }
  if (node.properties) {
    const properties: Record<string, unknown> = {}
    for (const [name, value] of Object.entries(node.properties)) properties[name] = templatable(value)
    inner.properties = properties
  }
  if (node.items) inner.items = templatable(node.items)

  // A string field already accepts a template, and a field with no type
  // accepts anything.
  if (type === undefined || type === 'string' || (Array.isArray(type) && type.includes('string'))) {
    return inner
  }

  const { description, ...rest } = inner
  return {
    ...(description ? { description } : {}),
    anyOf: [rest, { type: 'string', pattern: '^\\$\\{.+\\}$' }]
  }
}

/** The ten fields of a test, and everything else is an annotation. */
function test(): Record<string, unknown> {
  return {
    type: 'object',
    required: ['steps'],
    properties: {
      id: { type: 'string', description: "the test's identity: stable, and what every event carries" },
      name: { type: 'string', description: 'the older spelling of `id`, still read' },
      title: { type: 'string', description: 'the sentence a person reads, when the identity is not one' },
      tags: { type: 'array', items: { type: 'string' }, description: 'what --tags filters on' },
      pending: { type: 'string', description: 'why this test is not being run — a reason, not a flag' },
      timeout: {
        type: ['integer', 'string'],
        description: "the longest the whole test may take — 5000, or '30s'; cleanup gets its own budget"
      },
      variables: { type: 'object', description: 'the givens, resolved once in declaration order' },
      cases: { type: 'array', description: 'a table of inputs — one test per row, each with its own id' },
      setup: { $ref: '#/definitions/steps' },
      steps: { $ref: '#/definitions/steps' },
      assert: { $ref: '#/definitions/assertions' },
      cleanup: { $ref: '#/definitions/steps' },
      meta: { type: 'object', description: 'annotations, carried and never read' }
    },
    // Open on purpose: everything outside the spine is an annotation, and the
    // list has to be closed for the annotations to be open.
    additionalProperties: true
  }
}

function suite(): Record<string, unknown> {
  return {
    type: 'object',
    properties: {
      // What tells the two apart, and it has to be said this way round. A
      // manifest declares no body, and without this the open annotation space
      // on a suite would make every file a valid suite — including a test
      // file with a misspelled key in it, which is the whole thing this is
      // for. Found by running the generated schema through a validator.
      steps: false,
      title: { type: 'string' },
      tags: { type: 'array', items: { type: 'string' } },
      pending: { type: 'string', description: 'parks every test below, with one reason' },
      setup: { $ref: '#/definitions/steps' },
      cleanup: { $ref: '#/definitions/steps' },
      meta: { type: 'object' }
    },
    additionalProperties: true
  }
}
